// Code generated by protoc-gen-go. DO NOT EDIT.
// source: books.proto

package books

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}

var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}

func (Person_PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{3, 0}
}

type Borrower struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	Person               *Person  `protobuf:"bytes,2,opt,name=person,proto3" json:"person,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Borrower) Reset()         { *m = Borrower{} }
func (m *Borrower) String() string { return proto.CompactTextString(m) }
func (*Borrower) ProtoMessage()    {}
func (*Borrower) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{0}
}

func (m *Borrower) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Borrower.Unmarshal(m, b)
}
func (m *Borrower) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Borrower.Marshal(b, m, deterministic)
}
func (m *Borrower) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Borrower.Merge(m, src)
}
func (m *Borrower) XXX_Size() int {
	return xxx_messageInfo_Borrower.Size(m)
}
func (m *Borrower) XXX_DiscardUnknown() {
	xxx_messageInfo_Borrower.DiscardUnknown(m)
}

var xxx_messageInfo_Borrower proto.InternalMessageInfo

func (m *Borrower) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

func (m *Borrower) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

func (m *Borrower) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Book struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{1}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Book) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Status struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{2}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Person struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Email                string                `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phones               []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
	LastUpdated          *timestamp.Timestamp  `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{3}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

func (m *Person) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type Person_PhoneNumber struct {
	Number               string           `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 Person_PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=books.Person_PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Person_PhoneNumber) Reset()         { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()    {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{3, 0}
}

func (m *Person_PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person_PhoneNumber.Unmarshal(m, b)
}
func (m *Person_PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *Person_PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person_PhoneNumber.Merge(m, src)
}
func (m *Person_PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_Person_PhoneNumber.Size(m)
}
func (m *Person_PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_Person_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_Person_PhoneNumber proto.InternalMessageInfo

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_MOBILE
}

type AddressBook struct {
	People               []*Person `protobuf:"bytes,1,rep,name=people,proto3" json:"people,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddressBook) Reset()         { *m = AddressBook{} }
func (m *AddressBook) String() string { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()    {}
func (*AddressBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e0dc127ded4184, []int{4}
}

func (m *AddressBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressBook.Unmarshal(m, b)
}
func (m *AddressBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressBook.Marshal(b, m, deterministic)
}
func (m *AddressBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressBook.Merge(m, src)
}
func (m *AddressBook) XXX_Size() int {
	return xxx_messageInfo_AddressBook.Size(m)
}
func (m *AddressBook) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressBook.DiscardUnknown(m)
}

var xxx_messageInfo_AddressBook proto.InternalMessageInfo

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterEnum("books.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
	proto.RegisterType((*Borrower)(nil), "books.Borrower")
	proto.RegisterType((*Book)(nil), "books.Book")
	proto.RegisterType((*Status)(nil), "books.Status")
	proto.RegisterType((*Person)(nil), "books.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "books.Person.PhoneNumber")
	proto.RegisterType((*AddressBook)(nil), "books.AddressBook")
}

func init() { proto.RegisterFile("books.proto", fileDescriptor_01e0dc127ded4184) }

var fileDescriptor_01e0dc127ded4184 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0x2f, 0x69, 0xb2, 0x5e, 0x27, 0x7a, 0x96, 0x41, 0x34, 0xe6, 0xe5, 0x4a, 0x40, 0x28,
	0x77, 0x90, 0xc3, 0x78, 0xaf, 0x3e, 0x18, 0x38, 0x50, 0xb4, 0xb6, 0xac, 0x15, 0x1f, 0x25, 0x21,
	0x6b, 0x0d, 0x4d, 0xb2, 0xcb, 0xee, 0x06, 0xe9, 0x07, 0xf3, 0xfb, 0xc9, 0xee, 0x26, 0x45, 0xa1,
	0x0f, 0xbe, 0xcd, 0xec, 0xfc, 0xe6, 0x9f, 0xc9, 0x7f, 0x06, 0xa2, 0x8a, 0xf3, 0x83, 0xca, 0x84,
	0xe4, 0x9a, 0x63, 0x68, 0x93, 0xe4, 0x7a, 0xcf, 0xf9, 0xbe, 0x65, 0x77, 0xf6, 0xb1, 0x1a, 0x7e,
	0xdc, 0xe9, 0xa6, 0x63, 0x4a, 0x97, 0x9d, 0x70, 0x5c, 0x5a, 0xc1, 0x65, 0xc1, 0xa5, 0xe4, 0xbf,
	0x98, 0xc4, 0x6b, 0x08, 0x4c, 0x57, 0xec, 0x2d, 0xbd, 0x55, 0x94, 0x47, 0x99, 0xd3, 0x2b, 0x38,
	0x3f, 0x50, 0x5b, 0xc0, 0x57, 0x40, 0x04, 0x93, 0x8a, 0xf7, 0xb1, 0x6f, 0x91, 0x27, 0x23, 0xb2,
	0xb5, 0x8f, 0x74, 0x2c, 0xe2, 0x15, 0xf8, 0x4d, 0x1d, 0xcf, 0x96, 0xde, 0x6a, 0x4e, 0xfd, 0xa6,
	0x4e, 0x6f, 0x20, 0x30, 0x22, 0x88, 0x10, 0xf4, 0x65, 0xc7, 0xac, 0xfe, 0x9c, 0xda, 0x78, 0x64,
	0x8d, 0x5c, 0x68, 0xd9, 0x14, 0xc8, 0x17, 0x5d, 0xea, 0x41, 0x61, 0x0c, 0x8f, 0x3a, 0xa6, 0x54,
	0xb9, 0x9f, 0x1a, 0xa6, 0x34, 0xfd, 0xed, 0x03, 0x71, 0x9f, 0xfc, 0x1f, 0x49, 0x7c, 0x06, 0x21,
	0xeb, 0xca, 0xa6, 0x1d, 0x27, 0x72, 0x09, 0xbe, 0x06, 0x22, 0x7e, 0xf2, 0x9e, 0xa9, 0x38, 0x58,
	0xce, 0x56, 0x51, 0xfe, 0xf2, 0x9f, 0x7f, 0xc9, 0xb6, 0xa6, 0xf6, 0x79, 0xe8, 0x2a, 0x26, 0xe9,
	0x08, 0xe2, 0x5b, 0x78, 0xdc, 0x96, 0x4a, 0x7f, 0x1f, 0x44, 0x5d, 0x6a, 0x56, 0xc7, 0xa1, 0x35,
	0x21, 0xc9, 0x9c, 0xc7, 0xd9, 0xe4, 0x71, 0xb6, 0x9b, 0x3c, 0xa6, 0x91, 0xe1, 0xbf, 0x3a, 0x3c,
	0xa1, 0x10, 0xfd, 0xa5, 0x8a, 0xcf, 0x81, 0xf4, 0x36, 0x1a, 0x87, 0x1f, 0x33, 0xbc, 0x85, 0x40,
	0x1f, 0x05, 0xb3, 0x3f, 0x70, 0x95, 0xbf, 0x38, 0x33, 0xd6, 0xee, 0x28, 0x18, 0xb5, 0x50, 0x7a,
	0x0b, 0xf3, 0xd3, 0x13, 0x02, 0x90, 0xf5, 0xa6, 0xf8, 0xf0, 0xe9, 0x61, 0x71, 0x81, 0x97, 0x10,
	0xbc, 0xdf, 0xac, 0x1f, 0x16, 0x9e, 0x89, 0xbe, 0x6d, 0xe8, 0xc7, 0x85, 0x9f, 0xde, 0x43, 0xf4,
	0xae, 0xae, 0x25, 0x53, 0xaa, 0x38, 0x6d, 0x93, 0x8b, 0xd6, 0xb8, 0x37, 0x3b, 0xbb, 0x4d, 0x53,
	0xcc, 0xef, 0x81, 0x18, 0x9c, 0x49, 0xbc, 0x31, 0x91, 0xb9, 0x15, 0x7c, 0x7a, 0xba, 0x0d, 0x77,
	0x3a, 0xc9, 0xd4, 0xeb, 0x76, 0x97, 0x5e, 0x54, 0xc4, 0xba, 0xf1, 0xe6, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xb5, 0x86, 0xe6, 0xed, 0x95, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookerClient is the client API for Booker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookerClient interface {
	Borrow(ctx context.Context, in *Borrower, opts ...grpc.CallOption) (*Status, error)
}

type bookerClient struct {
	cc *grpc.ClientConn
}

func NewBookerClient(cc *grpc.ClientConn) BookerClient {
	return &bookerClient{cc}
}

func (c *bookerClient) Borrow(ctx context.Context, in *Borrower, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/books.Booker/Borrow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookerServer is the server API for Booker service.
type BookerServer interface {
	Borrow(context.Context, *Borrower) (*Status, error)
}

// UnimplementedBookerServer can be embedded to have forward compatible implementations.
type UnimplementedBookerServer struct {
}

func (*UnimplementedBookerServer) Borrow(ctx context.Context, req *Borrower) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Borrow not implemented")
}

func RegisterBookerServer(s *grpc.Server, srv BookerServer) {
	s.RegisterService(&_Booker_serviceDesc, srv)
}

func _Booker_Borrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Borrower)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookerServer).Borrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/books.Booker/Borrow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookerServer).Borrow(ctx, req.(*Borrower))
	}
	return interceptor(ctx, in, info, handler)
}

var _Booker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "books.Booker",
	HandlerType: (*BookerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Borrow",
			Handler:    _Booker_Borrow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "books.proto",
}
