// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.2
// source: play.proto

package v1advanced

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//description of 5W1H principal
type BuzzPlay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buzz  *Buzz  `protobuf:"bytes,1,opt,name=buzz,proto3" json:"buzz,omitempty"`
	Where []byte `protobuf:"bytes,2,opt,name=where,proto3" json:"where,omitempty"` //(12.34, 2452.2, 1235.22)
	Who   []byte `protobuf:"bytes,3,opt,name=who,proto3" json:"who,omitempty"`     //user
	How   []byte `protobuf:"bytes,4,opt,name=how,proto3" json:"how,omitempty"`     //skill, weapon
	What  []byte `protobuf:"bytes,5,opt,name=what,proto3" json:"what,omitempty"`   // monster, user, none
	Why   []byte `protobuf:"bytes,6,opt,name=why,proto3" json:"why,omitempty"`     // hunting, quest, none
}

func (x *BuzzPlay) Reset() {
	*x = BuzzPlay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_play_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuzzPlay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuzzPlay) ProtoMessage() {}

func (x *BuzzPlay) ProtoReflect() protoreflect.Message {
	mi := &file_play_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuzzPlay.ProtoReflect.Descriptor instead.
func (*BuzzPlay) Descriptor() ([]byte, []int) {
	return file_play_proto_rawDescGZIP(), []int{0}
}

func (x *BuzzPlay) GetBuzz() *Buzz {
	if x != nil {
		return x.Buzz
	}
	return nil
}

func (x *BuzzPlay) GetWhere() []byte {
	if x != nil {
		return x.Where
	}
	return nil
}

func (x *BuzzPlay) GetWho() []byte {
	if x != nil {
		return x.Who
	}
	return nil
}

func (x *BuzzPlay) GetHow() []byte {
	if x != nil {
		return x.How
	}
	return nil
}

func (x *BuzzPlay) GetWhat() []byte {
	if x != nil {
		return x.What
	}
	return nil
}

func (x *BuzzPlay) GetWhy() []byte {
	if x != nil {
		return x.Why
	}
	return nil
}

var File_play_proto protoreflect.FileDescriptor

var file_play_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x76, 0x31,
	0x61, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x64, 0x1a, 0x0e, 0x61, 0x64, 0x76, 0x61, 0x6e, 0x63,
	0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x01, 0x0a, 0x08, 0x42, 0x75, 0x7a,
	0x7a, 0x50, 0x6c, 0x61, 0x79, 0x12, 0x24, 0x0a, 0x04, 0x62, 0x75, 0x7a, 0x7a, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x31, 0x61, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x64,
	0x2e, 0x42, 0x75, 0x7a, 0x7a, 0x52, 0x04, 0x62, 0x75, 0x7a, 0x7a, 0x12, 0x14, 0x0a, 0x05, 0x77,
	0x68, 0x65, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x77, 0x68, 0x65, 0x72,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x68, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x77, 0x68, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x68, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x68, 0x61, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x77, 0x68, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x68, 0x79,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x77, 0x68, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_play_proto_rawDescOnce sync.Once
	file_play_proto_rawDescData = file_play_proto_rawDesc
)

func file_play_proto_rawDescGZIP() []byte {
	file_play_proto_rawDescOnce.Do(func() {
		file_play_proto_rawDescData = protoimpl.X.CompressGZIP(file_play_proto_rawDescData)
	})
	return file_play_proto_rawDescData
}

var file_play_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_play_proto_goTypes = []interface{}{
	(*BuzzPlay)(nil), // 0: v1advanced.BuzzPlay
	(*Buzz)(nil),     // 1: v1advanced.Buzz
}
var file_play_proto_depIdxs = []int32{
	1, // 0: v1advanced.BuzzPlay.buzz:type_name -> v1advanced.Buzz
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_play_proto_init() }
func file_play_proto_init() {
	if File_play_proto != nil {
		return
	}
	file_advanced_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_play_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuzzPlay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_play_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_play_proto_goTypes,
		DependencyIndexes: file_play_proto_depIdxs,
		MessageInfos:      file_play_proto_msgTypes,
	}.Build()
	File_play_proto = out.File
	file_play_proto_rawDesc = nil
	file_play_proto_goTypes = nil
	file_play_proto_depIdxs = nil
}
