version: "3"
services:
  # 배포용 이미지
  # calc:
  #   build:
  #     context: 
  #   ports:
  #     - "8000:8000"
  # 디버깅용 이미지
  calc-debug:
    build:
      context: ../
      dockerfile: ./remote-debugging-tdd/debug/Dockerfile
    ports:
      - "8001:8000"
      - "2345:2345"