/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: play.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "play.pb-c.h"
void   v1advanced__buzz_play__init
                     (V1advanced__BuzzPlay         *message)
{
  static const V1advanced__BuzzPlay init_value = V1ADVANCED__BUZZ_PLAY__INIT;
  *message = init_value;
}
size_t v1advanced__buzz_play__get_packed_size
                     (const V1advanced__BuzzPlay *message)
{
  assert(message->base.descriptor == &v1advanced__buzz_play__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t v1advanced__buzz_play__pack
                     (const V1advanced__BuzzPlay *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &v1advanced__buzz_play__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t v1advanced__buzz_play__pack_to_buffer
                     (const V1advanced__BuzzPlay *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &v1advanced__buzz_play__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
V1advanced__BuzzPlay *
       v1advanced__buzz_play__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (V1advanced__BuzzPlay *)
     protobuf_c_message_unpack (&v1advanced__buzz_play__descriptor,
                                allocator, len, data);
}
void   v1advanced__buzz_play__free_unpacked
                     (V1advanced__BuzzPlay *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &v1advanced__buzz_play__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor v1advanced__buzz_play__field_descriptors[6] =
{
  {
    "buzz",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(V1advanced__BuzzPlay, buzz),
    &v1advanced__buzz__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "where",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(V1advanced__BuzzPlay, where),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "who",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(V1advanced__BuzzPlay, who),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "how",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(V1advanced__BuzzPlay, how),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "what",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(V1advanced__BuzzPlay, what),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "why",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(V1advanced__BuzzPlay, why),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned v1advanced__buzz_play__field_indices_by_name[] = {
  0,   /* field[0] = buzz */
  3,   /* field[3] = how */
  4,   /* field[4] = what */
  1,   /* field[1] = where */
  2,   /* field[2] = who */
  5,   /* field[5] = why */
};
static const ProtobufCIntRange v1advanced__buzz_play__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor v1advanced__buzz_play__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "v1advanced.BuzzPlay",
  "BuzzPlay",
  "V1advanced__BuzzPlay",
  "v1advanced",
  sizeof(V1advanced__BuzzPlay),
  6,
  v1advanced__buzz_play__field_descriptors,
  v1advanced__buzz_play__field_indices_by_name,
  1,  v1advanced__buzz_play__number_ranges,
  (ProtobufCMessageInit) v1advanced__buzz_play__init,
  NULL,NULL,NULL    /* reserved[123] */
};
