/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: play.proto */

#ifndef PROTOBUF_C_play_2eproto__INCLUDED
#define PROTOBUF_C_play_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "advanced.pb-c.h"

typedef struct _V1advanced__BuzzPlay V1advanced__BuzzPlay;


/* --- enums --- */


/* --- messages --- */

/*
 *description of 5W1H principal
 */
struct  _V1advanced__BuzzPlay
{
  ProtobufCMessage base;
  V1advanced__Buzz *buzz;
  /*
   *(12.34, 2452.2, 1235.22)
   */
  ProtobufCBinaryData where;
  /*
   *user
   */
  ProtobufCBinaryData who;
  /*
   *skill, weapon
   */
  ProtobufCBinaryData how;
  /*
   * monster, user, none
   */
  ProtobufCBinaryData what;
  /*
   * hunting, quest, none
   */
  ProtobufCBinaryData why;
};
#define V1ADVANCED__BUZZ_PLAY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&v1advanced__buzz_play__descriptor) \
    , NULL, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL} }


/* V1advanced__BuzzPlay methods */
void   v1advanced__buzz_play__init
                     (V1advanced__BuzzPlay         *message);
size_t v1advanced__buzz_play__get_packed_size
                     (const V1advanced__BuzzPlay   *message);
size_t v1advanced__buzz_play__pack
                     (const V1advanced__BuzzPlay   *message,
                      uint8_t             *out);
size_t v1advanced__buzz_play__pack_to_buffer
                     (const V1advanced__BuzzPlay   *message,
                      ProtobufCBuffer     *buffer);
V1advanced__BuzzPlay *
       v1advanced__buzz_play__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   v1advanced__buzz_play__free_unpacked
                     (V1advanced__BuzzPlay *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*V1advanced__BuzzPlay_Closure)
                 (const V1advanced__BuzzPlay *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor v1advanced__buzz_play__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_play_2eproto__INCLUDED */
